### ISSUE TITLE
fn bind(&mut self...) is invalid pointer

### ISSUE THREAD

**Issue by ripread** [vberger/wayland-rs#108]
https://gist.github.com/ripread/6defcb029653faff45c577d16f913d3d
I compiled the client code with `gcc -lwayland-client client.c`

    $ rust-gdb compositor
    (gdb) b compositor::{{impl}}::bind
    (gdb) run
    Breakpoint 1, compositor::{{impl}}::bind (self=0x1, evqh=0x3, global=WlCompositor = {...})

As you can see, both self and evqh are invalid pointers.

**Comment by ripread** [comment]
$rust-gdb compositor
    (gdb) b  wayland_server::event_loop::global_bind::{{closure}}<wayland_server::generated::server::wl_compositor::WlCompositor,rwc::CompositorGlobal>
    (gdb) run
    Breakpoint 1 ...
    let data = &*(data as ...);
    (gdb) n
    let handler = data.0;
    (gdb) print data[0]
    $1 = {0x1, 0x3}

So the self pointer is already invalid when global_bind is called

**Comment by ripread** [comment]
The `data = Box::new(...)` in register_global has the same address as data in global_bind, some somewhere betwen the two something's overwriting that memory.

**Comment by vberger** [comment]
Okay, this is very concerning.

Running your first code, I get this 

```
Breakpoint 1, compositor::{{impl}}::bind (self=0xc000100000001, evqh=0x3, global=WlCompositor = {...})
```

Looks like I only get `evqh` to be corrupted, not `self` ? Are your running this on wayland-server 0.9.3 ?

The second one gives me the same thing: `$1 = {0xc000100000001, 0x3}`

**Comment by vberger** [comment]
well no, looks like when the user data is set in `register_global`, the values are `{0x7ffff6636000, 0x7ffff661f060}`...

**Comment by vberger** [comment]
Oh well...

```
Hardware watchpoint 2: *0x7ffff6636010

Old value = -161259520
New value = 0
0x00007ffff7bd3bdd in wl_map_insert_at () from /usr/lib/libwayland-server.so.0
```

**Comment by vberger** [comment]
Alright, found. When the `Global` object returned by `register_global` is destroyed, it frees the backing storage of the user data...

This is plainly wrong, as it's documented that you can let it go out of scope. I'll correct this.
