### ISSUE TITLE
register_with_destructor gives invalid pointer to RUST_MANAGED in dispatch_func

### ISSUE THREAD

**Issue by ripread** [vberger/wayland-rs#110]
This code errors out with a `[wayland-client error] Dispatcher got called for a message on a non-managed object.`    
https://gist.github.com/ripread/6defcb029653faff45c577d16f913d3d

When inspecting dispatch_func, `_impl` is a pointer to some stack value as opposed to the static RUST_MANAGED. Changing compositor.rs:21 to evqh.register<...> fixes the issue (although it does error out because of the null buffer).

This can also be seen in smithay:shm:mod.rs:220. Attempting to wl_shm_pool_create_buffer(...) in client code gives the same non-managed object error, and changing this line to evqh.register<...> fixes the issue, although now the destructor isn't being called.

**Comment by ripread** [comment]
odd bug as register directly calls register_with_destructor

**Comment by vberger** [comment]
Are you using wayland-server 0.9.3 ? A bug regarding RUST_MANAGED had just been fixed in it

**Comment by vberger** [comment]
Nvm, I guess you are using master, as otherwise your example fails due to the previous bug...

**Comment by vberger** [comment]
Okay, running your code I just get a SIGSEGV, so I guess it must be some other memory corruption somewhere...

**Comment by vberger** [comment]
@ripread I've pushed a fix for a bug I found. With this fix, your example runs fine for me.

However, I never reproduced your symptoms, so please tell me if it fixes it for you too.

**Comment by ripread** [comment]
I am using wayland-server 0.9.3. I'm having difficulty compiling the git version though so I haven't testesd myself if the most recent changes fixed it for me

**Comment by vberger** [comment]
Well, I'll release a 0.9.4 including the two last fixes then.

**Comment by vberger** [comment]
Done. you can update to it and tell me how it gets. :)

**Comment by ripread** [comment]
All working!

**Comment by vberger** [comment]
Good. I think I'll integrate your small example as a test, I'm in need of those!
