### ISSUE TITLE
Mapping correct keysym for wayland client with keyboard

### ISSUE THREAD

**Issue by Timidger** [vberger/wayland-rs#115]
Hey there. I'm trying to simply print out the associated key when the keysym is provided to the `wl_keyboard::Handler::key` callback using the `xkbcommon` crate.

However, I evidently need to use [this method](http://rtbo.github.io/xkbcommon-rs/xkbcommon/xkb/struct.State.html#method.key_get_one_sym) because the symbol ids given to me in the method don't correspond to the correct key, unfortunately I'm not sure how I am able to construct that with the information provided to the client (Do I need to use the `RawFd` provided in the `keymap` callback?).

Should I be using a different method to map keys to their string representations, or do I need to construct a `xkb::State` somehow?

Here's what I have, which is not printing the correct character when I press it on the keyboard:

    fn key(&mut self,
           evqh: &mut EventQueueHandle,
           proxy: &wl_keyboard::WlKeyboard,
           serial: u32,
           time: u32,
           key: u32,
           state: wl_keyboard::KeyState) {
        if state == wl_keyboard::KeyState::Pressed {
            println!("Number: {:#?}", key);
            println!("Got key: {:#?}", xkb::keysym_get_name(key));
            // self.input is just a string made up of all the keys pressed so far
            self.input.push_str(keysym_to_utf8(key).as_str());
            println!("Input is: {}", self.input);
        }
    }

**Comment by vberger** [comment]
I don't have a very usable Internet access for a few days. But maybe you can take inspiration from the code of https://github.com/vberger/wayland-kbd (if you don't want to use it directly) , which if I'm not misunderstanding does exactly what you want.

**Comment by vberger** [comment]
(looks like my link to the documentation in the Readme of wayland-kbd is outdated, you'll find the up to date API docs on docs.rs, sorry for that)

**Comment by Timidger** [comment]
Ah, ok. I had seen that crate but for some reason assumed it was deprecated (the yanked version of it on crates.io probably made me think that). I'll use that then, thanks!

**Comment by vberger** [comment]
Yeah, I just messed up with semver and remembering how cargo handle dependency. 

I need to bump the version om wayland-kbd to handle latest wayland-client I believe, but there is no actual code change needed. I can do that on after the weekend.

**Comment by vberger** [comment]
I've just published wayland-kbd 0.9.0 :)
