### ISSUE TITLE
Problem when implementing wl_surface handler

### ISSUE THREAD

**Issue by fangyuanziti** [vberger/wayland-rs#99]
Currrently, I am trying to use this `wayland-server` crate to implement my wayland compositor.
However, I am stuck in the wl_surface::Handler interface.
```rust
impl wl_surface::Handler for SurfaceHandler {
 fn attach(&mut self,
              _evqh: &mut EventLoopHandle,
              _client: &Client,
              _resource: &WlSurface,
              _buffer: Option<&WlBuffer>,
              _x: i32,
           _y: i32) {
  // my surface logic
 }
```
To get a workable wl_surface handler, I need to implement the `attach` function. According to the Wayland api reference, I think I need store `_buffer` in somewhere as pending buffer. But the `_buffer`'s type (Option<&WlBuffer>) makes the work diffcult. I can't store it because of the lifetime logic in rust.
Do you have some suggestion about this. Maybe this is not a issue about this crate, If I am wrong, please tell me. Thanks.

**Comment by vberger** [comment]
This is a very good question, and something I was expecting to hit eventually in smithay.

I think I'll try to make `Resource`s objects `Clone`. I've been wondering about making this for some time now, mostly for the reasons you are describing right now. And it's about time doing it.

However, it'll need some work to ensure the safety of all this, as these objects can be destroyed anytime by the client, and sending events to destroyed objects would cause all sorts of weird error and state corruption.

I'll see if I can make it work, I have an idea.

**Comment by fangyuanziti** [comment]
Thanks for your reply. look forward for it. :smile:

**Comment by vberger** [comment]
Actually, Resources are now cloneable since version 0.9.1 using the [`Resource::clone`](https://docs.rs/wayland-server/0.9.1/wayland_server/trait.Resource.html#method.clone) method. Sorry I forgot to update this issue after releasing it.

**Comment by fangyuanziti** [comment]
Thanks for you work.
